preload = $HOME/dotfiles/hyprpaper/.config/hypr/hyprpapers/*

wallpaper {
    monitor = DP-1
    path = $HOME/dotfiles/hyprpaper/.config/hypr/hyprpapers
    fit_mode = fill
    timeout = 10
    order = random
    recursive = false
}

wallpaper {
    monitor = DP-2
    path = $HOME/dotfiles/hyprpaper/.config/hypr/hyprpapers
    fit_mode = fill
    timeout = 10
    order = random
    recursive = false
}

ipc = true
splash = true
splash_offset = 20
splash_opacity = 0.8
