preload = ~/.config/hypr/hyprpapers/*

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/hyprpapers/
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/hyprpapers/
    fit_mode = cover
}

splash = true
splash_offset = 20
splash_opacity = 0.5
